/**
 * Prebuild script — detects the host machine's current LAN IP and writes it
 * into src/environments/environment.ts so the Capacitor iOS app can reach
 * the local backend without a hardcoded address.
 *
 * Run automatically via "prestart" and "prebuild" hooks in package.json.
 */

import { networkInterfaces } from 'os';
import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dir, '../src/environments');
const outFile = join(outDir, 'environment.ts');

function getLanIp() {
  for (const ifaces of Object.values(networkInterfaces())) {
    for (const iface of ifaces ?? []) {
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  return '127.0.0.1';
}

const ip = getLanIp();

mkdirSync(outDir, { recursive: true });

writeFileSync(outFile, `// Auto-generated by scripts/set-dev-ip.mjs — do not edit manually.
// Re-generated on every \`npm start\` and \`npm run build\`.
export const environment = {
  devMachineIp: '${ip}',
};
`);

console.log(`[set-dev-ip] devMachineIp set to ${ip}`);
